#!/usr/bin/env bash

set -euo pipefail

# Generated by ops-script-maintenance scaffold.
# Update with: python3 .codex/skills/ops-script-maintenance/scripts/scaffold_manage.py --root .

PROJECT_PROFILE=generic
HAS_PYTHON=0
PYTHON_REQUIREMENT=''
PYTHON_HAS_PYPROJECT=0
PYTHON_HAS_REQUIREMENTS=0
NODE_PACKAGE_DIRS=()
NODE_DEV_DIRS=()
NODE_BUILD_DIRS=()
NODE_TEST_DIRS=()

SCRIPT_NAME="manage.sh"
THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${THIS_DIR}/.." && pwd)"
LOCAL_ENV_FILE="${ROOT_DIR}/.codex-helper/local-env.toml"
NPM_REGISTRY="${CODEX_HELPER_NPM_REGISTRY:-}"
NPM_REGISTRY_MIRROR="${CODEX_HELPER_NPM_REGISTRY_MIRROR:-}"
UV_DEFAULT_INDEX="${UV_DEFAULT_INDEX:-${CODEX_HELPER_UV_DEFAULT_INDEX:-}}"
PIP_INDEX="${PIP_INDEX_URL:-}"
PIP_EXTRA_INDEX="${PIP_EXTRA_INDEX_URL:-}"
UV_INSTALL_URL="${CODEX_HELPER_UV_INSTALL_URL:-}"
UV_PYTHON_INSTALL_MIRROR="${CODEX_HELPER_UV_PYTHON_INSTALL_MIRROR:-}"
NODE_MIRROR="${CODEX_HELPER_NODE_MIRROR:-}"
DOCKER_REGISTRY_MIRROR="${CODEX_HELPER_DOCKER_REGISTRY_MIRROR:-}"
DOCKER_IMAGE_PREFIX="${CODEX_HELPER_DOCKER_IMAGE_PREFIX:-}"
DOCKER_BASE_IMAGE="${CODEX_HELPER_DOCKER_BASE_IMAGE:-}"
NODE_DOCKER_IMAGE="${CODEX_HELPER_NODE_DOCKER_IMAGE:-}"
DOCKER_VM_IMAGE="${CODEX_HELPER_DOCKER_VM_IMAGE:-}"
DEBIAN_MIRROR="${CODEX_HELPER_DEBIAN_MIRROR:-}"
NODE_APT_REPO="${CODEX_HELPER_NODE_APT_REPO:-}"

HOST="127.0.0.1"
PORT=""
STATE_DIR=""
INSTALL_MISSING=0
SKIP_START=0
SYSTEMD_DEPLOY=0
TARGET_USER="${USER:-}"
SERVICE_NAME="$(basename "${ROOT_DIR}")"
EXEC_COMMAND=""

log() {
  printf '[%s] %s\n' "${SCRIPT_NAME}" "$*"
}

warn() {
  printf '[%s] warning: %s\n' "${SCRIPT_NAME}" "$*" >&2
}

die() {
  printf '[%s] error: %s\n' "${SCRIPT_NAME}" "$*" >&2
  exit 1
}

valid_service_name() {
  [[ "${1}" =~ ^[A-Za-z0-9][A-Za-z0-9_.@-]*$ ]]
}

resolve_user_home() {
  local user_name="$1"
  python3 - "$user_name" <<'PY'
import pwd
import sys

try:
    print(pwd.getpwnam(sys.argv[1]).pw_dir)
except KeyError:
    raise SystemExit(1)
PY
}

usage() {
  cat <<EOF
Usage: bash deploy/manage.sh <command> [options]

Commands:
  detect-env             Detect local tools and write .codex-helper/local-env.toml
  setup                  Prepare repo-local Python/Node dependencies
  dev                    Start detected foreground dev scripts
  build                  Run detected build scripts; pass --systemd for a service file
  doctor                 Print detected facts and missing dependency guidance

Options:
  --host HOST            Host for service metadata (default: ${HOST})
  --port PORT            Port for service metadata
  --state-dir PATH       Runtime state directory
  --install-missing      Print supported install guidance before failing on missing tools
  --skip-start           Print commands without starting dev processes
  --systemd              build: write a Linux systemd service
  --user USER            build --systemd: service user
  --service-name NAME    build --systemd: service name
  --exec-command CMD     build --systemd: ExecStart command
  --help                 Show this help
EOF
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --host)
        [[ $# -ge 2 ]] || die "missing value for --host"
        HOST="$2"; shift 2 ;;
      --port)
        [[ $# -ge 2 ]] || die "missing value for --port"
        PORT="$2"; shift 2 ;;
      --state-dir)
        [[ $# -ge 2 ]] || die "missing value for --state-dir"
        STATE_DIR="$2"; shift 2 ;;
      --install-missing)
        INSTALL_MISSING=1; shift ;;
      --skip-start)
        SKIP_START=1; shift ;;
      --systemd)
        SYSTEMD_DEPLOY=1; shift ;;
      --user)
        [[ $# -ge 2 ]] || die "missing value for --user"
        TARGET_USER="$2"; shift 2 ;;
      --service-name)
        [[ $# -ge 2 ]] || die "missing value for --service-name"
        SERVICE_NAME="$2"; shift 2 ;;
      --exec-command)
        [[ $# -ge 2 ]] || die "missing value for --exec-command"
        EXEC_COMMAND="$2"; shift 2 ;;
      --help|-h)
        usage; exit 0 ;;
      *)
        die "unknown argument: $1" ;;
    esac
  done
  STATE_DIR="${STATE_DIR:-${HOME}/.codex-helper/state}"
}

host_os() {
  uname -s | tr '[:upper:]' '[:lower:]'
}

is_macos() {
  [[ "$(host_os)" == "darwin" ]]
}

is_linux() {
  [[ "$(host_os)" == "linux" ]]
}

distro_id() {
  if [[ -r /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    printf '%s\n' "${ID:-linux}"
    return
  fi
  if is_macos; then
    printf 'macos\n'
    return
  fi
  printf 'unknown\n'
}

service_manager() {
  if command -v systemctl >/dev/null 2>&1; then
    printf 'systemd\n'
  elif is_macos; then
    printf 'launchd\n'
  else
    printf 'none\n'
  fi
}

command_path() {
  local command_name="$1"
  if [[ "${command_name}" == */* ]]; then
    [[ -x "${command_name}" ]] && printf '%s\n' "${command_name}"
    return
  fi
  command -v "${command_name}" 2>/dev/null || true
}

command_version() {
  local command_name="$1"
  [[ -n "${command_name}" ]] || return 0
  if [[ "${command_name}" != */* ]] && ! command -v "${command_name}" >/dev/null 2>&1; then
    return 0
  fi
  "${command_name}" --version 2>&1 | head -n 1 || true
}

select_python() {
  if [[ -x "${ROOT_DIR}/.venv/bin/python" ]]; then
    printf '%s\n' "${ROOT_DIR}/.venv/bin/python"
    return
  fi
  command_path python3 || command_path python || true
}

relative_repo_dir() {
  local path="$1"
  local prefix="${ROOT_DIR}/"
  if [[ "${path}" == "${ROOT_DIR}" ]]; then
    printf '.\n'
  elif [[ "${path}" == "${prefix}"* ]]; then
    printf '%s\n' "${path#${prefix}}"
  else
    printf '%s\n' "${path}"
  fi
}

tool_source() {
  local path="$1"
  case "${path}" in
    "") printf 'missing' ;;
    "${ROOT_DIR}/.venv/"*) printf 'repo-venv' ;;
    "${ROOT_DIR}/node_modules/"*|"${ROOT_DIR}"/*/node_modules/*) printf 'repo-node_modules' ;;
    */.nvm/*) printf 'nvm' ;;
    */.conda/*|*/miniforge*|*/anaconda*) printf 'conda' ;;
    /opt/homebrew/*|/usr/local/Homebrew/*) printf 'homebrew' ;;
    /usr/bin/*|/bin/*|/usr/local/bin/*|/opt/*) printf 'system' ;;
    *) printf 'path' ;;
  esac
}

toml_string() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "${value}"
}

write_tool_table() {
  local name="$1"
  local command_name="$2"
  local now="$3"
  local path version
  path="$(command_path "${command_name}")"
  version="$(command_version "${path:-${command_name}}")"
  printf '[tools.%s]\n' "${name}"
  printf 'command = '; toml_string "${path}"; printf '\n'
  printf 'path = '; toml_string "${path}"; printf '\n'
  printf 'version = '; toml_string "${version}"; printf '\n'
  printf 'source = '; toml_string "$(tool_source "${path}")"; printf '\n'
  printf 'verified_at = '; toml_string "${now}"; printf '\n\n'
}

write_package_manager_table() {
  local name="$1"
  local command_name="$2"
  local path
  path="$(command_path "${command_name}")"
  printf '[package_managers.%s]\n' "${name}"
  if [[ -n "${path}" ]]; then
    printf 'available = true\n'
  else
    printf 'available = false\n'
  fi
  printf 'path = '; toml_string "${path}"; printf '\n\n'
}

proxy_detected() {
  if [[ -n "${HTTPS_PROXY:-${https_proxy:-${HTTP_PROXY:-${http_proxy:-}}}}" ]]; then
    printf 'true\n'
  else
    printf 'false\n'
  fi
}

dependency_source_has_secret() {
  local value="$1"
  local lower
  lower="$(printf '%s' "${value}" | tr '[:upper:]' '[:lower:]')"
  [[ "${lower}" == *"_authtoken"* ]] && return 0
  [[ "${lower}" == *"authorization"* ]] && return 0
  [[ "${lower}" == *"bearer "* ]] && return 0
  [[ "${lower}" == *"password="* ]] && return 0
  [[ "${lower}" == *"passwd="* ]] && return 0
  [[ "${lower}" == *"token="* ]] && return 0
  [[ "${lower}" == *"secret="* ]] && return 0
  [[ "${value}" =~ ^[a-zA-Z][a-zA-Z0-9+.-]*://[^/@]+:[^/@]+@ ]] && return 0
  return 1
}

redact_dependency_source() {
  local value="$1"
  if [[ -n "${value}" ]] && dependency_source_has_secret "${value}"; then
    printf '[redacted-secret-bearing-url]'
  else
    printf '%s' "${value}"
  fi
}

detect_env() {
  mkdir -p "${ROOT_DIR}/.codex-helper"
  local now os_name distribution version arch shell_name service python_cmd
  now="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  os_name="$(uname -s)"
  distribution="$(distro_id)"
  version=""
  if is_macos; then
    version="$(sw_vers -productVersion 2>/dev/null || true)"
  elif [[ -r /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    version="${VERSION_ID:-}"
  fi
  arch="$(uname -m)"
  shell_name="${SHELL:-}"
  service="$(service_manager)"
  python_cmd="$(select_python)"

  {
    printf '[meta]\n'
    printf 'schema_version = 1\n'
    printf 'project_root = '; toml_string "${ROOT_DIR}"; printf '\n'
    printf 'generated_at = '; toml_string "${now}"; printf '\n'
    printf 'generated_by = "deploy/manage.sh detect-env"\n'
    printf 'last_verified_at = '; toml_string "${now}"; printf '\n\n'

    printf '[system]\n'
    printf 'os = '; toml_string "${os_name}"; printf '\n'
    if is_macos; then
      printf 'os_family = "macos"\n'
    elif is_linux; then
      printf 'os_family = "linux"\n'
    else
      printf 'os_family = "unknown"\n'
    fi
    printf 'distribution = '; toml_string "${distribution}"; printf '\n'
    printf 'version = '; toml_string "${version}"; printf '\n'
    printf 'arch = '; toml_string "${arch}"; printf '\n'
    printf 'shell = '; toml_string "${shell_name}"; printf '\n'
    if grep -qi microsoft /proc/version 2>/dev/null; then
      printf 'is_wsl = true\n'
    else
      printf 'is_wsl = false\n'
    fi
    printf 'service_manager = '; toml_string "${service}"; printf '\n\n'

    write_tool_table python "${python_cmd:-python3}" "${now}"
    write_tool_table uv uv "${now}"
    write_tool_table node node "${now}"
    write_tool_table npm npm "${now}"
    write_tool_table codex codex "${now}"
    write_tool_table git git "${now}"

    printf '[requirements]\n'
    printf 'python = '; toml_string "${PYTHON_REQUIREMENT}"; printf '\n'
    printf 'node_major = '; toml_string "${CODEX_HELPER_NODE_MAJOR:-}"; printf '\n'
    printf 'codex_package = '; toml_string "${CODEX_HELPER_CODEX_PACKAGE_SPEC:-}"; printf '\n'
    printf 'python_source = "pyproject.toml"\n'
    printf 'node_source = ""\n\n'

    printf '[paths]\n'
    printf 'python_bin_dir = '; toml_string "$(relative_repo_dir "${ROOT_DIR}/.venv/bin")"; printf '\n'
    if [[ -f "${ROOT_DIR}/web/package.json" ]]; then
      printf 'node_bin_dir = '; toml_string "$(relative_repo_dir "${ROOT_DIR}/web/node_modules/.bin")"; printf '\n'
    else
      printf 'node_bin_dir = '; toml_string "$(relative_repo_dir "${ROOT_DIR}/node_modules/.bin")"; printf '\n'
    fi
    printf 'extra_bin_dirs = []\n'
    printf 'venv_dir = '; toml_string "$(relative_repo_dir "${ROOT_DIR}/.venv")"; printf '\n'
    printf 'state_dir = ""\n\n'

    write_package_manager_table homebrew brew
    write_package_manager_table apt apt-get
    write_package_manager_table dnf dnf
    write_package_manager_table yum yum
    write_package_manager_table nvm nvm
    write_package_manager_table conda conda

    printf '[dependency_sources]\n'
    printf 'docker_registry_mirror = '; toml_string "$(redact_dependency_source "${DOCKER_REGISTRY_MIRROR}")"; printf '\n'
    printf 'docker_image_prefix = '; toml_string "$(redact_dependency_source "${DOCKER_IMAGE_PREFIX}")"; printf '\n'
    printf 'docker_base_image = '; toml_string "$(redact_dependency_source "${DOCKER_BASE_IMAGE}")"; printf '\n'
    printf 'node_docker_image = '; toml_string "$(redact_dependency_source "${NODE_DOCKER_IMAGE}")"; printf '\n'
    printf 'docker_vm_image = '; toml_string "$(redact_dependency_source "${DOCKER_VM_IMAGE}")"; printf '\n'
    printf 'debian_mirror = '; toml_string "$(redact_dependency_source "${DEBIAN_MIRROR}")"; printf '\n'
    printf 'node_apt_repo = '; toml_string "$(redact_dependency_source "${NODE_APT_REPO}")"; printf '\n'
    printf 'npm_registry = '; toml_string "$(redact_dependency_source "${NPM_REGISTRY}")"; printf '\n'
    printf 'npm_registry_mirror = '; toml_string "$(redact_dependency_source "${NPM_REGISTRY_MIRROR}")"; printf '\n'
    printf 'uv_index = '; toml_string "$(redact_dependency_source "${UV_DEFAULT_INDEX}")"; printf '\n'
    printf 'pip_index = '; toml_string "$(redact_dependency_source "${PIP_INDEX}")"; printf '\n'
    printf 'pip_extra_index = '; toml_string "$(redact_dependency_source "${PIP_EXTRA_INDEX}")"; printf '\n'
    printf 'python_install_mirror = '; toml_string "$(redact_dependency_source "${UV_PYTHON_INSTALL_MIRROR}")"; printf '\n'
    printf 'uv_install_url = '; toml_string "$(redact_dependency_source "${UV_INSTALL_URL}")"; printf '\n'
    printf 'node_install_mirror = '; toml_string "$(redact_dependency_source "${NODE_MIRROR}")"; printf '\n'
    printf 'proxy_detected = '; proxy_detected; printf '\n'
    printf 'source = "deploy/manage.sh detect-env"\n\n'

    printf '[policy]\n'
    printf 'dependency_strategy = "reuse-first"\n'
    printf 'auto_install = false\n'
    printf 'project_isolation = true\n\n'

    printf '[verification]\n'
    printf 'last_detect_env_at = '; toml_string "${now}"; printf '\n'
    printf 'last_doctor_at = ""\n'
    printf 'drift_detected = false\n'
  } > "${LOCAL_ENV_FILE}"
  log "wrote ${LOCAL_ENV_FILE}"
}

package_path() {
  local relative_dir="$1"
  if [[ "${relative_dir}" == "." ]]; then
    printf '%s\n' "${ROOT_DIR}"
  else
    printf '%s/%s\n' "${ROOT_DIR}" "${relative_dir}"
  fi
}

missing_commands() {
  local missing=()
  command -v git >/dev/null 2>&1 || missing+=(git)
  if [[ "${HAS_PYTHON}" -eq 1 ]]; then
    command -v uv >/dev/null 2>&1 || missing+=(uv)
  fi
  if [[ "${#NODE_PACKAGE_DIRS[@]}" -gt 0 ]]; then
    command -v node >/dev/null 2>&1 || missing+=(node)
    command -v npm >/dev/null 2>&1 || missing+=(npm)
  fi
  if [[ "${#missing[@]}" -gt 0 ]]; then
    printf '%s\n' "${missing[@]}"
  fi
}

print_install_guidance() {
  local distro
  distro="$(distro_id)"
  echo "Missing dependency guidance:"
  if is_macos; then
    echo "  brew install git uv node"
  elif [[ "${distro}" =~ ^(ubuntu|debian)$ ]]; then
    echo "  sudo apt-get update && sudo apt-get install -y git curl ca-certificates nodejs npm"
    echo "  curl -LsSf https://astral.sh/uv/install.sh | sh"
  elif [[ "${distro}" =~ ^(centos|rhel|rocky|almalinux|fedora)$ ]]; then
    echo "  sudo dnf install -y git curl ca-certificates nodejs npm || sudo yum install -y git curl ca-certificates nodejs npm"
    echo "  curl -LsSf https://astral.sh/uv/install.sh | sh"
  else
    echo "  Install git, uv, Node, and npm with this host's package manager as needed."
  fi
}

ensure_dependencies_or_explain() {
  local missing
  missing="$(missing_commands || true)"
  if [[ -z "${missing}" ]]; then
    return
  fi
  if [[ "${INSTALL_MISSING}" -eq 1 ]]; then
    warn "this scaffold prints install guidance but does not mutate system packages automatically"
  fi
  printf '[%s] error: missing required commands: %s\n' "${SCRIPT_NAME}" "${missing//$'\n'/, }" >&2
  print_install_guidance >&2
  exit 1
}

sync_python_env() {
  [[ "${HAS_PYTHON}" -eq 1 ]] || return
  command -v uv >/dev/null 2>&1 || die "uv is required for Python dependency sync"
  (
    cd "${ROOT_DIR}"
    if [[ "${PYTHON_HAS_PYPROJECT}" -eq 1 ]]; then
      if [[ -f uv.lock ]]; then
        uv sync --frozen
      else
        uv sync
      fi
    elif [[ "${PYTHON_HAS_REQUIREMENTS}" -eq 1 ]]; then
      uv venv .venv
      uv pip install -r requirements.txt
    else
      warn "Python project detected, but no supported dependency file was found"
    fi
  )
}

sync_node_dependencies() {
  local relative_dir package_dir
  for relative_dir in "${NODE_PACKAGE_DIRS[@]}"; do
    package_dir="$(package_path "${relative_dir}")"
    if [[ -f "${package_dir}/package-lock.json" ]]; then
      npm ci --prefix "${package_dir}"
    else
      npm install --prefix "${package_dir}"
    fi
  done
}

setup_command() {
  parse_args "$@"
  detect_env
  ensure_dependencies_or_explain
  sync_python_env
  sync_node_dependencies
  detect_env
  log "setup complete for profile ${PROJECT_PROFILE}"
}

print_dev_plan() {
  local relative_dir package_dir
  if [[ "${HAS_PYTHON}" -eq 1 ]]; then
    echo "Python dev command: not inferred; customize deploy/manage.sh for this app's server entrypoint."
  fi
  for relative_dir in "${NODE_DEV_DIRS[@]}"; do
    package_dir="$(package_path "${relative_dir}")"
    echo "Node dev command: npm --prefix $(printf '%q' "${package_dir}") run dev"
  done
  if [[ "${#NODE_DEV_DIRS[@]}" -eq 0 && "${HAS_PYTHON}" -eq 0 ]]; then
    echo "No dev command inferred for profile ${PROJECT_PROFILE}."
  fi
}

dev_command() {
  parse_args "$@"
  detect_env
  if [[ "${SKIP_START}" -eq 1 ]]; then
    print_dev_plan
    return
  fi
  ensure_dependencies_or_explain
  local pids=()
  local relative_dir package_dir
  for relative_dir in "${NODE_DEV_DIRS[@]}"; do
    package_dir="$(package_path "${relative_dir}")"
    npm --prefix "${package_dir}" run dev &
    pids+=("$!")
  done
  if [[ "${#pids[@]}" -eq 0 ]]; then
    print_dev_plan
    return
  fi
  trap 'kill "${pids[@]}" 2>/dev/null || true' EXIT INT TERM
  while true; do
    local alive=0 pid
    for pid in "${pids[@]}"; do
      if kill -0 "${pid}" 2>/dev/null; then
        alive=1
      fi
    done
    [[ "${alive}" -eq 1 ]] || break
    sleep 1
  done
  wait "${pids[@]}" 2>/dev/null || true
}

run_builds() {
  local relative_dir package_dir
  if [[ "${HAS_PYTHON}" -eq 1 && "${PYTHON_HAS_PYPROJECT}" -eq 1 ]]; then
    command -v uv >/dev/null 2>&1 || die "uv is required for Python build"
    (cd "${ROOT_DIR}" && uv build)
  fi
  for relative_dir in "${NODE_BUILD_DIRS[@]}"; do
    package_dir="$(package_path "${relative_dir}")"
    npm --prefix "${package_dir}" run build
  done
}

write_systemd_service() {
  is_linux || die "--systemd is supported on Linux only"
  [[ "$(service_manager)" == "systemd" ]] || die "--systemd requires systemd"
  [[ "$(id -u)" -eq 0 ]] || die "--systemd requires root so service files can be written"
  [[ -n "${TARGET_USER}" ]] || die "--systemd requires --user"
  [[ -n "${EXEC_COMMAND}" ]] || die "--systemd requires --exec-command"
  valid_service_name "${SERVICE_NAME}" || die "invalid service name: ${SERVICE_NAME}"
  local target_home target_group env_file service_file
  target_home="$(resolve_user_home "${TARGET_USER}")" || die "unable to resolve home for ${TARGET_USER}"
  [[ -d "${target_home}" ]] || die "unable to resolve home for ${TARGET_USER}"
  target_group="$(id -gn "${TARGET_USER}")"
  if [[ -z "${STATE_DIR}" || "${STATE_DIR}" == "${HOME}/.codex-helper/state" ]]; then
    STATE_DIR="${target_home}/.codex-helper/state"
  fi
  mkdir -p "${STATE_DIR}"
  env_file="/etc/default/${SERVICE_NAME}"
  service_file="/etc/systemd/system/${SERVICE_NAME}.service"
  cat > "${env_file}" <<EOF
HOME=${target_home}
USER=${TARGET_USER}
LOGNAME=${TARGET_USER}
CODEX_HELPER_STATE_HOME_DIR=${STATE_DIR}
CODEX_HELPER_WEB_HOST=${HOST}
CODEX_HELPER_WEB_PORT=${PORT}
EOF
  cat > "${service_file}" <<EOF
[Unit]
Description=${SERVICE_NAME}
After=network.target

[Service]
Type=simple
User=${TARGET_USER}
Group=${target_group}
WorkingDirectory=${ROOT_DIR}
EnvironmentFile=-${env_file}
ExecStart=${EXEC_COMMAND}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  if [[ "${SKIP_START}" -eq 1 ]]; then
    warn "systemd reload/start skipped; run 'systemctl daemon-reload && systemctl restart ${SERVICE_NAME}' manually"
  else
    systemctl daemon-reload
    systemctl enable "${SERVICE_NAME}" >/dev/null
    systemctl restart "${SERVICE_NAME}"
  fi
  echo "Environment file: ${env_file}"
  echo "Service file: ${service_file}"
}

build_command() {
  parse_args "$@"
  detect_env
  ensure_dependencies_or_explain
  sync_python_env
  sync_node_dependencies
  run_builds
  if [[ "${SYSTEMD_DEPLOY}" -eq 1 ]]; then
    write_systemd_service
  fi
}

doctor_command() {
  parse_args "$@"
  detect_env
  echo
  echo "Project profile: ${PROJECT_PROFILE}"
  echo "Node packages: ${NODE_PACKAGE_DIRS[*]:-(none)}"
  echo
  sed -n '1,220p' "${LOCAL_ENV_FILE}"
  echo
  local missing
  missing="$(missing_commands || true)"
  if [[ -n "${missing}" ]]; then
    printf 'Missing commands: %s\n' "${missing//$'\n'/, }"
    print_install_guidance
  else
    echo "Required commands for this profile are available in the current shell."
  fi
  echo
  echo "Dependency source diagnostics:"
  [[ -n "${DOCKER_REGISTRY_MIRROR}" ]] && echo "  docker_registry_mirror=$(redact_dependency_source "${DOCKER_REGISTRY_MIRROR}")"
  [[ -n "${DOCKER_IMAGE_PREFIX}" ]] && echo "  docker_image_prefix=$(redact_dependency_source "${DOCKER_IMAGE_PREFIX}")"
  [[ -n "${DOCKER_BASE_IMAGE}" ]] && echo "  docker_base_image=$(redact_dependency_source "${DOCKER_BASE_IMAGE}")"
  [[ -n "${NODE_DOCKER_IMAGE}" ]] && echo "  node_docker_image=$(redact_dependency_source "${NODE_DOCKER_IMAGE}")"
  [[ -n "${DOCKER_VM_IMAGE}" ]] && echo "  docker_vm_image=$(redact_dependency_source "${DOCKER_VM_IMAGE}")"
  [[ -n "${DEBIAN_MIRROR}" ]] && echo "  debian_mirror=$(redact_dependency_source "${DEBIAN_MIRROR}")"
  [[ -n "${NODE_APT_REPO}" ]] && echo "  node_apt_repo=$(redact_dependency_source "${NODE_APT_REPO}")"
  echo "  npm_registry=$(redact_dependency_source "${NPM_REGISTRY}")"
  [[ -n "${NPM_REGISTRY_MIRROR}" ]] && echo "  npm_registry_mirror=$(redact_dependency_source "${NPM_REGISTRY_MIRROR}")"
  [[ -n "${UV_DEFAULT_INDEX}" ]] && echo "  uv_index=$(redact_dependency_source "${UV_DEFAULT_INDEX}")"
  [[ -n "${PIP_INDEX}" ]] && echo "  pip_index=$(redact_dependency_source "${PIP_INDEX}")"
  [[ -n "${PIP_EXTRA_INDEX}" ]] && echo "  pip_extra_index=$(redact_dependency_source "${PIP_EXTRA_INDEX}")"
  [[ -n "${UV_PYTHON_INSTALL_MIRROR}" ]] && echo "  python_install_mirror=$(redact_dependency_source "${UV_PYTHON_INSTALL_MIRROR}")"
  [[ -n "${NODE_MIRROR}" ]] && echo "  node_install_mirror=$(redact_dependency_source "${NODE_MIRROR}")"
  echo "  proxy_detected=$(proxy_detected)"
}

main() {
  local command_name="${1:-}"
  [[ -n "${command_name}" ]] || { usage; exit 1; }
  shift || true
  case "${command_name}" in
    detect-env) parse_args "$@"; detect_env ;;
    setup) setup_command "$@" ;;
    dev) dev_command "$@" ;;
    build) build_command "$@" ;;
    doctor) doctor_command "$@" ;;
    --help|-h|help) usage ;;
    *) die "unknown command: ${command_name}" ;;
  esac
}

main "$@"
