#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shlex
import stat
import subprocess
from dataclasses import dataclass
from pathlib import Path

GENERATED_MARKER = "Generated by ops-script-maintenance scaffold."


@dataclass(frozen=True)
class NodePackage:
    relative_dir: str
    has_dev: bool
    has_build: bool
    has_test: bool


@dataclass(frozen=True)
class ProjectProfile:
    has_python: bool
    python_requirement: str
    has_pyproject: bool
    has_requirements: bool
    node_packages: tuple[NodePackage, ...]

    @property
    def name(self) -> str:
        parts: list[str] = []
        if self.has_python:
            parts.append("python")
        if self.node_packages:
            parts.append("node")
        return "-".join(parts) if parts else "generic"


def discover_profile(root: Path) -> ProjectProfile:
    has_pyproject = (root / "pyproject.toml").exists()
    has_requirements = (root / "requirements.txt").exists()
    has_python = has_pyproject or has_requirements or (root / "setup.py").exists()
    python_requirement = _read_pyproject_python(root) if has_pyproject else ""
    return ProjectProfile(
        has_python=has_python,
        python_requirement=python_requirement,
        has_pyproject=has_pyproject,
        has_requirements=has_requirements,
        node_packages=tuple(_discover_node_packages(root)),
    )


def _read_pyproject_python(root: Path) -> str:
    try:
        text = (root / "pyproject.toml").read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("requires-python") and "=" in stripped:
            return stripped.split("=", 1)[1].strip().strip('"').strip("'")
    return ""


def _discover_node_packages(root: Path) -> list[NodePackage]:
    candidates = [Path(".")]
    candidates.extend(Path(name) for name in ("web", "frontend", "client", "app", "ui"))
    packages: list[NodePackage] = []
    seen: set[str] = set()
    for relative_dir in candidates:
        package_path = root / relative_dir / "package.json"
        if not package_path.exists():
            continue
        normalized = relative_dir.as_posix()
        if normalized in seen:
            continue
        seen.add(normalized)
        payload = _load_json(package_path)
        scripts = payload.get("scripts", {}) if isinstance(payload, dict) else {}
        scripts = scripts if isinstance(scripts, dict) else {}
        packages.append(
            NodePackage(
                relative_dir=normalized,
                has_dev="dev" in scripts,
                has_build="build" in scripts,
                has_test="test" in scripts,
            )
        )
    return packages


def _load_json(path: Path) -> dict[str, object]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def render_manage_script(profile: ProjectProfile) -> str:
    node_dirs = tuple(item.relative_dir for item in profile.node_packages)
    node_dev_dirs = tuple(item.relative_dir for item in profile.node_packages if item.has_dev)
    node_build_dirs = tuple(item.relative_dir for item in profile.node_packages if item.has_build)
    node_test_dirs = tuple(item.relative_dir for item in profile.node_packages if item.has_test)
    lines = [
        "#!/usr/bin/env bash",
        "",
        "set -euo pipefail",
        "",
        f"# {GENERATED_MARKER}",
        "# Update with: python3 .codex/skills/ops-script-maintenance/scripts/scaffold_manage.py --root .",
        "",
        f"PROJECT_PROFILE={shlex.quote(profile.name)}",
        f"HAS_PYTHON={1 if profile.has_python else 0}",
        f"PYTHON_REQUIREMENT={shlex.quote(profile.python_requirement)}",
        f"PYTHON_HAS_PYPROJECT={1 if profile.has_pyproject else 0}",
        f"PYTHON_HAS_REQUIREMENTS={1 if profile.has_requirements else 0}",
        f"NODE_PACKAGE_DIRS={_bash_array(node_dirs)}",
        f"NODE_DEV_DIRS={_bash_array(node_dev_dirs)}",
        f"NODE_BUILD_DIRS={_bash_array(node_build_dirs)}",
        f"NODE_TEST_DIRS={_bash_array(node_test_dirs)}",
        MANAGE_BODY.rstrip(),
        "",
    ]
    return "\n".join(lines)


def _bash_array(values: tuple[str, ...]) -> str:
    if not values:
        return "()"
    return "(" + " ".join(shlex.quote(value) for value in values) + ")"


MANAGE_BODY = r'''
SCRIPT_NAME="manage.sh"
THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${THIS_DIR}/.." && pwd)"
LOCAL_ENV_FILE="${ROOT_DIR}/.codex-helper/local-env.toml"
NPM_REGISTRY="${CODEX_HELPER_NPM_REGISTRY:-}"
NPM_REGISTRY_MIRROR="${CODEX_HELPER_NPM_REGISTRY_MIRROR:-}"
UV_DEFAULT_INDEX="${UV_DEFAULT_INDEX:-${CODEX_HELPER_UV_DEFAULT_INDEX:-}}"
PIP_INDEX="${PIP_INDEX_URL:-}"
PIP_EXTRA_INDEX="${PIP_EXTRA_INDEX_URL:-}"
UV_INSTALL_URL="${CODEX_HELPER_UV_INSTALL_URL:-}"
UV_PYTHON_INSTALL_MIRROR="${CODEX_HELPER_UV_PYTHON_INSTALL_MIRROR:-}"
NODE_MIRROR="${CODEX_HELPER_NODE_MIRROR:-}"
DOCKER_REGISTRY_MIRROR="${CODEX_HELPER_DOCKER_REGISTRY_MIRROR:-}"
DOCKER_IMAGE_PREFIX="${CODEX_HELPER_DOCKER_IMAGE_PREFIX:-}"
DOCKER_BASE_IMAGE="${CODEX_HELPER_DOCKER_BASE_IMAGE:-}"
NODE_DOCKER_IMAGE="${CODEX_HELPER_NODE_DOCKER_IMAGE:-}"
DOCKER_VM_IMAGE="${CODEX_HELPER_DOCKER_VM_IMAGE:-}"
DEBIAN_MIRROR="${CODEX_HELPER_DEBIAN_MIRROR:-}"
NODE_APT_REPO="${CODEX_HELPER_NODE_APT_REPO:-}"

HOST="127.0.0.1"
PORT=""
STATE_DIR=""
INSTALL_MISSING=0
SKIP_START=0
SYSTEMD_DEPLOY=0
TARGET_USER="${USER:-}"
SERVICE_NAME="$(basename "${ROOT_DIR}")"
EXEC_COMMAND=""

log() {
  printf '[%s] %s\n' "${SCRIPT_NAME}" "$*"
}

warn() {
  printf '[%s] warning: %s\n' "${SCRIPT_NAME}" "$*" >&2
}

die() {
  printf '[%s] error: %s\n' "${SCRIPT_NAME}" "$*" >&2
  exit 1
}

valid_service_name() {
  [[ "${1}" =~ ^[A-Za-z0-9][A-Za-z0-9_.@-]*$ ]]
}

resolve_user_home() {
  local user_name="$1"
  python3 - "$user_name" <<'PY'
import pwd
import sys

try:
    print(pwd.getpwnam(sys.argv[1]).pw_dir)
except KeyError:
    raise SystemExit(1)
PY
}

usage() {
  cat <<EOF
Usage: bash deploy/manage.sh <command> [options]

Commands:
  detect-env             Detect local tools and write .codex-helper/local-env.toml
  setup                  Prepare repo-local Python/Node dependencies
  dev                    Start detected foreground dev scripts
  build                  Run detected build scripts; pass --systemd for a service file
  doctor                 Print detected facts and missing dependency guidance

Options:
  --host HOST            Host for service metadata (default: ${HOST})
  --port PORT            Port for service metadata
  --state-dir PATH       Runtime state directory
  --install-missing      Print supported install guidance before failing on missing tools
  --skip-start           Print commands without starting dev processes
  --systemd              build: write a Linux systemd service
  --user USER            build --systemd: service user
  --service-name NAME    build --systemd: service name
  --exec-command CMD     build --systemd: ExecStart command
  --help                 Show this help
EOF
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --host)
        [[ $# -ge 2 ]] || die "missing value for --host"
        HOST="$2"; shift 2 ;;
      --port)
        [[ $# -ge 2 ]] || die "missing value for --port"
        PORT="$2"; shift 2 ;;
      --state-dir)
        [[ $# -ge 2 ]] || die "missing value for --state-dir"
        STATE_DIR="$2"; shift 2 ;;
      --install-missing)
        INSTALL_MISSING=1; shift ;;
      --skip-start)
        SKIP_START=1; shift ;;
      --systemd)
        SYSTEMD_DEPLOY=1; shift ;;
      --user)
        [[ $# -ge 2 ]] || die "missing value for --user"
        TARGET_USER="$2"; shift 2 ;;
      --service-name)
        [[ $# -ge 2 ]] || die "missing value for --service-name"
        SERVICE_NAME="$2"; shift 2 ;;
      --exec-command)
        [[ $# -ge 2 ]] || die "missing value for --exec-command"
        EXEC_COMMAND="$2"; shift 2 ;;
      --help|-h)
        usage; exit 0 ;;
      *)
        die "unknown argument: $1" ;;
    esac
  done
  STATE_DIR="${STATE_DIR:-${HOME}/.codex-helper/state}"
}

host_os() {
  uname -s | tr '[:upper:]' '[:lower:]'
}

is_macos() {
  [[ "$(host_os)" == "darwin" ]]
}

is_linux() {
  [[ "$(host_os)" == "linux" ]]
}

distro_id() {
  if [[ -r /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    printf '%s\n' "${ID:-linux}"
    return
  fi
  if is_macos; then
    printf 'macos\n'
    return
  fi
  printf 'unknown\n'
}

service_manager() {
  if command -v systemctl >/dev/null 2>&1; then
    printf 'systemd\n'
  elif is_macos; then
    printf 'launchd\n'
  else
    printf 'none\n'
  fi
}

command_path() {
  local command_name="$1"
  if [[ "${command_name}" == */* ]]; then
    [[ -x "${command_name}" ]] && printf '%s\n' "${command_name}"
    return
  fi
  command -v "${command_name}" 2>/dev/null || true
}

command_version() {
  local command_name="$1"
  [[ -n "${command_name}" ]] || return 0
  if [[ "${command_name}" != */* ]] && ! command -v "${command_name}" >/dev/null 2>&1; then
    return 0
  fi
  "${command_name}" --version 2>&1 | head -n 1 || true
}

select_python() {
  if [[ -x "${ROOT_DIR}/.venv/bin/python" ]]; then
    printf '%s\n' "${ROOT_DIR}/.venv/bin/python"
    return
  fi
  command_path python3 || command_path python || true
}

relative_repo_dir() {
  local path="$1"
  local prefix="${ROOT_DIR}/"
  if [[ "${path}" == "${ROOT_DIR}" ]]; then
    printf '.\n'
  elif [[ "${path}" == "${prefix}"* ]]; then
    printf '%s\n' "${path#${prefix}}"
  else
    printf '%s\n' "${path}"
  fi
}

tool_source() {
  local path="$1"
  case "${path}" in
    "") printf 'missing' ;;
    "${ROOT_DIR}/.venv/"*) printf 'repo-venv' ;;
    "${ROOT_DIR}/node_modules/"*|"${ROOT_DIR}"/*/node_modules/*) printf 'repo-node_modules' ;;
    */.nvm/*) printf 'nvm' ;;
    */.conda/*|*/miniforge*|*/anaconda*) printf 'conda' ;;
    /opt/homebrew/*|/usr/local/Homebrew/*) printf 'homebrew' ;;
    /usr/bin/*|/bin/*|/usr/local/bin/*|/opt/*) printf 'system' ;;
    *) printf 'path' ;;
  esac
}

toml_string() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "${value}"
}

write_tool_table() {
  local name="$1"
  local command_name="$2"
  local now="$3"
  local path version
  path="$(command_path "${command_name}")"
  version="$(command_version "${path:-${command_name}}")"
  printf '[tools.%s]\n' "${name}"
  printf 'command = '; toml_string "${path}"; printf '\n'
  printf 'path = '; toml_string "${path}"; printf '\n'
  printf 'version = '; toml_string "${version}"; printf '\n'
  printf 'source = '; toml_string "$(tool_source "${path}")"; printf '\n'
  printf 'verified_at = '; toml_string "${now}"; printf '\n\n'
}

write_package_manager_table() {
  local name="$1"
  local command_name="$2"
  local path
  path="$(command_path "${command_name}")"
  printf '[package_managers.%s]\n' "${name}"
  if [[ -n "${path}" ]]; then
    printf 'available = true\n'
  else
    printf 'available = false\n'
  fi
  printf 'path = '; toml_string "${path}"; printf '\n\n'
}

proxy_detected() {
  if [[ -n "${HTTPS_PROXY:-${https_proxy:-${HTTP_PROXY:-${http_proxy:-}}}}" ]]; then
    printf 'true\n'
  else
    printf 'false\n'
  fi
}

dependency_source_has_secret() {
  local value="$1"
  local lower
  lower="$(printf '%s' "${value}" | tr '[:upper:]' '[:lower:]')"
  [[ "${lower}" == *"_authtoken"* ]] && return 0
  [[ "${lower}" == *"authorization"* ]] && return 0
  [[ "${lower}" == *"bearer "* ]] && return 0
  [[ "${lower}" == *"password="* ]] && return 0
  [[ "${lower}" == *"passwd="* ]] && return 0
  [[ "${lower}" == *"token="* ]] && return 0
  [[ "${lower}" == *"secret="* ]] && return 0
  [[ "${value}" =~ ^[a-zA-Z][a-zA-Z0-9+.-]*://[^/@]+:[^/@]+@ ]] && return 0
  return 1
}

redact_dependency_source() {
  local value="$1"
  if [[ -n "${value}" ]] && dependency_source_has_secret "${value}"; then
    printf '[redacted-secret-bearing-url]'
  else
    printf '%s' "${value}"
  fi
}

detect_env() {
  mkdir -p "${ROOT_DIR}/.codex-helper"
  local now os_name distribution version arch shell_name service python_cmd
  now="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  os_name="$(uname -s)"
  distribution="$(distro_id)"
  version=""
  if is_macos; then
    version="$(sw_vers -productVersion 2>/dev/null || true)"
  elif [[ -r /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    version="${VERSION_ID:-}"
  fi
  arch="$(uname -m)"
  shell_name="${SHELL:-}"
  service="$(service_manager)"
  python_cmd="$(select_python)"

  {
    printf '[meta]\n'
    printf 'schema_version = 1\n'
    printf 'project_root = '; toml_string "${ROOT_DIR}"; printf '\n'
    printf 'generated_at = '; toml_string "${now}"; printf '\n'
    printf 'generated_by = "deploy/manage.sh detect-env"\n'
    printf 'last_verified_at = '; toml_string "${now}"; printf '\n\n'

    printf '[system]\n'
    printf 'os = '; toml_string "${os_name}"; printf '\n'
    if is_macos; then
      printf 'os_family = "macos"\n'
    elif is_linux; then
      printf 'os_family = "linux"\n'
    else
      printf 'os_family = "unknown"\n'
    fi
    printf 'distribution = '; toml_string "${distribution}"; printf '\n'
    printf 'version = '; toml_string "${version}"; printf '\n'
    printf 'arch = '; toml_string "${arch}"; printf '\n'
    printf 'shell = '; toml_string "${shell_name}"; printf '\n'
    if grep -qi microsoft /proc/version 2>/dev/null; then
      printf 'is_wsl = true\n'
    else
      printf 'is_wsl = false\n'
    fi
    printf 'service_manager = '; toml_string "${service}"; printf '\n\n'

    write_tool_table python "${python_cmd:-python3}" "${now}"
    write_tool_table uv uv "${now}"
    write_tool_table node node "${now}"
    write_tool_table npm npm "${now}"
    write_tool_table codex codex "${now}"
    write_tool_table git git "${now}"

    printf '[requirements]\n'
    printf 'python = '; toml_string "${PYTHON_REQUIREMENT}"; printf '\n'
    printf 'node_major = '; toml_string "${CODEX_HELPER_NODE_MAJOR:-}"; printf '\n'
    printf 'codex_package = '; toml_string "${CODEX_HELPER_CODEX_PACKAGE_SPEC:-}"; printf '\n'
    printf 'python_source = "pyproject.toml"\n'
    printf 'node_source = ""\n\n'

    printf '[paths]\n'
    printf 'python_bin_dir = '; toml_string "$(relative_repo_dir "${ROOT_DIR}/.venv/bin")"; printf '\n'
    if [[ -f "${ROOT_DIR}/web/package.json" ]]; then
      printf 'node_bin_dir = '; toml_string "$(relative_repo_dir "${ROOT_DIR}/web/node_modules/.bin")"; printf '\n'
    else
      printf 'node_bin_dir = '; toml_string "$(relative_repo_dir "${ROOT_DIR}/node_modules/.bin")"; printf '\n'
    fi
    printf 'extra_bin_dirs = []\n'
    printf 'venv_dir = '; toml_string "$(relative_repo_dir "${ROOT_DIR}/.venv")"; printf '\n'
    printf 'state_dir = ""\n\n'

    write_package_manager_table homebrew brew
    write_package_manager_table apt apt-get
    write_package_manager_table dnf dnf
    write_package_manager_table yum yum
    write_package_manager_table nvm nvm
    write_package_manager_table conda conda

    printf '[dependency_sources]\n'
    printf 'docker_registry_mirror = '; toml_string "$(redact_dependency_source "${DOCKER_REGISTRY_MIRROR}")"; printf '\n'
    printf 'docker_image_prefix = '; toml_string "$(redact_dependency_source "${DOCKER_IMAGE_PREFIX}")"; printf '\n'
    printf 'docker_base_image = '; toml_string "$(redact_dependency_source "${DOCKER_BASE_IMAGE}")"; printf '\n'
    printf 'node_docker_image = '; toml_string "$(redact_dependency_source "${NODE_DOCKER_IMAGE}")"; printf '\n'
    printf 'docker_vm_image = '; toml_string "$(redact_dependency_source "${DOCKER_VM_IMAGE}")"; printf '\n'
    printf 'debian_mirror = '; toml_string "$(redact_dependency_source "${DEBIAN_MIRROR}")"; printf '\n'
    printf 'node_apt_repo = '; toml_string "$(redact_dependency_source "${NODE_APT_REPO}")"; printf '\n'
    printf 'npm_registry = '; toml_string "$(redact_dependency_source "${NPM_REGISTRY}")"; printf '\n'
    printf 'npm_registry_mirror = '; toml_string "$(redact_dependency_source "${NPM_REGISTRY_MIRROR}")"; printf '\n'
    printf 'uv_index = '; toml_string "$(redact_dependency_source "${UV_DEFAULT_INDEX}")"; printf '\n'
    printf 'pip_index = '; toml_string "$(redact_dependency_source "${PIP_INDEX}")"; printf '\n'
    printf 'pip_extra_index = '; toml_string "$(redact_dependency_source "${PIP_EXTRA_INDEX}")"; printf '\n'
    printf 'python_install_mirror = '; toml_string "$(redact_dependency_source "${UV_PYTHON_INSTALL_MIRROR}")"; printf '\n'
    printf 'uv_install_url = '; toml_string "$(redact_dependency_source "${UV_INSTALL_URL}")"; printf '\n'
    printf 'node_install_mirror = '; toml_string "$(redact_dependency_source "${NODE_MIRROR}")"; printf '\n'
    printf 'proxy_detected = '; proxy_detected; printf '\n'
    printf 'source = "deploy/manage.sh detect-env"\n\n'

    printf '[policy]\n'
    printf 'dependency_strategy = "reuse-first"\n'
    printf 'auto_install = false\n'
    printf 'project_isolation = true\n\n'

    printf '[verification]\n'
    printf 'last_detect_env_at = '; toml_string "${now}"; printf '\n'
    printf 'last_doctor_at = ""\n'
    printf 'drift_detected = false\n'
  } > "${LOCAL_ENV_FILE}"
  log "wrote ${LOCAL_ENV_FILE}"
}

package_path() {
  local relative_dir="$1"
  if [[ "${relative_dir}" == "." ]]; then
    printf '%s\n' "${ROOT_DIR}"
  else
    printf '%s/%s\n' "${ROOT_DIR}" "${relative_dir}"
  fi
}

missing_commands() {
  local missing=()
  command -v git >/dev/null 2>&1 || missing+=(git)
  if [[ "${HAS_PYTHON}" -eq 1 ]]; then
    command -v uv >/dev/null 2>&1 || missing+=(uv)
  fi
  if [[ "${#NODE_PACKAGE_DIRS[@]}" -gt 0 ]]; then
    command -v node >/dev/null 2>&1 || missing+=(node)
    command -v npm >/dev/null 2>&1 || missing+=(npm)
  fi
  if [[ "${#missing[@]}" -gt 0 ]]; then
    printf '%s\n' "${missing[@]}"
  fi
}

print_install_guidance() {
  local distro
  distro="$(distro_id)"
  echo "Missing dependency guidance:"
  if is_macos; then
    echo "  brew install git uv node"
  elif [[ "${distro}" =~ ^(ubuntu|debian)$ ]]; then
    echo "  sudo apt-get update && sudo apt-get install -y git curl ca-certificates nodejs npm"
    echo "  curl -LsSf https://astral.sh/uv/install.sh | sh"
  elif [[ "${distro}" =~ ^(centos|rhel|rocky|almalinux|fedora)$ ]]; then
    echo "  sudo dnf install -y git curl ca-certificates nodejs npm || sudo yum install -y git curl ca-certificates nodejs npm"
    echo "  curl -LsSf https://astral.sh/uv/install.sh | sh"
  else
    echo "  Install git, uv, Node, and npm with this host's package manager as needed."
  fi
}

ensure_dependencies_or_explain() {
  local missing
  missing="$(missing_commands || true)"
  if [[ -z "${missing}" ]]; then
    return
  fi
  if [[ "${INSTALL_MISSING}" -eq 1 ]]; then
    warn "this scaffold prints install guidance but does not mutate system packages automatically"
  fi
  printf '[%s] error: missing required commands: %s\n' "${SCRIPT_NAME}" "${missing//$'\n'/, }" >&2
  print_install_guidance >&2
  exit 1
}

sync_python_env() {
  [[ "${HAS_PYTHON}" -eq 1 ]] || return
  command -v uv >/dev/null 2>&1 || die "uv is required for Python dependency sync"
  (
    cd "${ROOT_DIR}"
    if [[ "${PYTHON_HAS_PYPROJECT}" -eq 1 ]]; then
      if [[ -f uv.lock ]]; then
        uv sync --frozen
      else
        uv sync
      fi
    elif [[ "${PYTHON_HAS_REQUIREMENTS}" -eq 1 ]]; then
      uv venv .venv
      uv pip install -r requirements.txt
    else
      warn "Python project detected, but no supported dependency file was found"
    fi
  )
}

sync_node_dependencies() {
  local relative_dir package_dir
  for relative_dir in "${NODE_PACKAGE_DIRS[@]}"; do
    package_dir="$(package_path "${relative_dir}")"
    if [[ -f "${package_dir}/package-lock.json" ]]; then
      npm ci --prefix "${package_dir}"
    else
      npm install --prefix "${package_dir}"
    fi
  done
}

setup_command() {
  parse_args "$@"
  detect_env
  ensure_dependencies_or_explain
  sync_python_env
  sync_node_dependencies
  detect_env
  log "setup complete for profile ${PROJECT_PROFILE}"
}

print_dev_plan() {
  local relative_dir package_dir
  if [[ "${HAS_PYTHON}" -eq 1 ]]; then
    echo "Python dev command: not inferred; customize deploy/manage.sh for this app's server entrypoint."
  fi
  for relative_dir in "${NODE_DEV_DIRS[@]}"; do
    package_dir="$(package_path "${relative_dir}")"
    echo "Node dev command: npm --prefix $(printf '%q' "${package_dir}") run dev"
  done
  if [[ "${#NODE_DEV_DIRS[@]}" -eq 0 && "${HAS_PYTHON}" -eq 0 ]]; then
    echo "No dev command inferred for profile ${PROJECT_PROFILE}."
  fi
}

dev_command() {
  parse_args "$@"
  detect_env
  if [[ "${SKIP_START}" -eq 1 ]]; then
    print_dev_plan
    return
  fi
  ensure_dependencies_or_explain
  local pids=()
  local relative_dir package_dir
  for relative_dir in "${NODE_DEV_DIRS[@]}"; do
    package_dir="$(package_path "${relative_dir}")"
    npm --prefix "${package_dir}" run dev &
    pids+=("$!")
  done
  if [[ "${#pids[@]}" -eq 0 ]]; then
    print_dev_plan
    return
  fi
  trap 'kill "${pids[@]}" 2>/dev/null || true' EXIT INT TERM
  while true; do
    local alive=0 pid
    for pid in "${pids[@]}"; do
      if kill -0 "${pid}" 2>/dev/null; then
        alive=1
      fi
    done
    [[ "${alive}" -eq 1 ]] || break
    sleep 1
  done
  wait "${pids[@]}" 2>/dev/null || true
}

run_builds() {
  local relative_dir package_dir
  if [[ "${HAS_PYTHON}" -eq 1 && "${PYTHON_HAS_PYPROJECT}" -eq 1 ]]; then
    command -v uv >/dev/null 2>&1 || die "uv is required for Python build"
    (cd "${ROOT_DIR}" && uv build)
  fi
  for relative_dir in "${NODE_BUILD_DIRS[@]}"; do
    package_dir="$(package_path "${relative_dir}")"
    npm --prefix "${package_dir}" run build
  done
}

write_systemd_service() {
  is_linux || die "--systemd is supported on Linux only"
  [[ "$(service_manager)" == "systemd" ]] || die "--systemd requires systemd"
  [[ "$(id -u)" -eq 0 ]] || die "--systemd requires root so service files can be written"
  [[ -n "${TARGET_USER}" ]] || die "--systemd requires --user"
  [[ -n "${EXEC_COMMAND}" ]] || die "--systemd requires --exec-command"
  valid_service_name "${SERVICE_NAME}" || die "invalid service name: ${SERVICE_NAME}"
  local target_home target_group env_file service_file
  target_home="$(resolve_user_home "${TARGET_USER}")" || die "unable to resolve home for ${TARGET_USER}"
  [[ -d "${target_home}" ]] || die "unable to resolve home for ${TARGET_USER}"
  target_group="$(id -gn "${TARGET_USER}")"
  if [[ -z "${STATE_DIR}" || "${STATE_DIR}" == "${HOME}/.codex-helper/state" ]]; then
    STATE_DIR="${target_home}/.codex-helper/state"
  fi
  mkdir -p "${STATE_DIR}"
  env_file="/etc/default/${SERVICE_NAME}"
  service_file="/etc/systemd/system/${SERVICE_NAME}.service"
  cat > "${env_file}" <<EOF
HOME=${target_home}
USER=${TARGET_USER}
LOGNAME=${TARGET_USER}
CODEX_HELPER_STATE_HOME_DIR=${STATE_DIR}
CODEX_HELPER_WEB_HOST=${HOST}
CODEX_HELPER_WEB_PORT=${PORT}
EOF
  cat > "${service_file}" <<EOF
[Unit]
Description=${SERVICE_NAME}
After=network.target

[Service]
Type=simple
User=${TARGET_USER}
Group=${target_group}
WorkingDirectory=${ROOT_DIR}
EnvironmentFile=-${env_file}
ExecStart=${EXEC_COMMAND}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  if [[ "${SKIP_START}" -eq 1 ]]; then
    warn "systemd reload/start skipped; run 'systemctl daemon-reload && systemctl restart ${SERVICE_NAME}' manually"
  else
    systemctl daemon-reload
    systemctl enable "${SERVICE_NAME}" >/dev/null
    systemctl restart "${SERVICE_NAME}"
  fi
  echo "Environment file: ${env_file}"
  echo "Service file: ${service_file}"
}

build_command() {
  parse_args "$@"
  detect_env
  ensure_dependencies_or_explain
  sync_python_env
  sync_node_dependencies
  run_builds
  if [[ "${SYSTEMD_DEPLOY}" -eq 1 ]]; then
    write_systemd_service
  fi
}

doctor_command() {
  parse_args "$@"
  detect_env
  echo
  echo "Project profile: ${PROJECT_PROFILE}"
  echo "Node packages: ${NODE_PACKAGE_DIRS[*]:-(none)}"
  echo
  sed -n '1,220p' "${LOCAL_ENV_FILE}"
  echo
  local missing
  missing="$(missing_commands || true)"
  if [[ -n "${missing}" ]]; then
    printf 'Missing commands: %s\n' "${missing//$'\n'/, }"
    print_install_guidance
  else
    echo "Required commands for this profile are available in the current shell."
  fi
  echo
  echo "Dependency source diagnostics:"
  [[ -n "${DOCKER_REGISTRY_MIRROR}" ]] && echo "  docker_registry_mirror=$(redact_dependency_source "${DOCKER_REGISTRY_MIRROR}")"
  [[ -n "${DOCKER_IMAGE_PREFIX}" ]] && echo "  docker_image_prefix=$(redact_dependency_source "${DOCKER_IMAGE_PREFIX}")"
  [[ -n "${DOCKER_BASE_IMAGE}" ]] && echo "  docker_base_image=$(redact_dependency_source "${DOCKER_BASE_IMAGE}")"
  [[ -n "${NODE_DOCKER_IMAGE}" ]] && echo "  node_docker_image=$(redact_dependency_source "${NODE_DOCKER_IMAGE}")"
  [[ -n "${DOCKER_VM_IMAGE}" ]] && echo "  docker_vm_image=$(redact_dependency_source "${DOCKER_VM_IMAGE}")"
  [[ -n "${DEBIAN_MIRROR}" ]] && echo "  debian_mirror=$(redact_dependency_source "${DEBIAN_MIRROR}")"
  [[ -n "${NODE_APT_REPO}" ]] && echo "  node_apt_repo=$(redact_dependency_source "${NODE_APT_REPO}")"
  echo "  npm_registry=$(redact_dependency_source "${NPM_REGISTRY}")"
  [[ -n "${NPM_REGISTRY_MIRROR}" ]] && echo "  npm_registry_mirror=$(redact_dependency_source "${NPM_REGISTRY_MIRROR}")"
  [[ -n "${UV_DEFAULT_INDEX}" ]] && echo "  uv_index=$(redact_dependency_source "${UV_DEFAULT_INDEX}")"
  [[ -n "${PIP_INDEX}" ]] && echo "  pip_index=$(redact_dependency_source "${PIP_INDEX}")"
  [[ -n "${PIP_EXTRA_INDEX}" ]] && echo "  pip_extra_index=$(redact_dependency_source "${PIP_EXTRA_INDEX}")"
  [[ -n "${UV_PYTHON_INSTALL_MIRROR}" ]] && echo "  python_install_mirror=$(redact_dependency_source "${UV_PYTHON_INSTALL_MIRROR}")"
  [[ -n "${NODE_MIRROR}" ]] && echo "  node_install_mirror=$(redact_dependency_source "${NODE_MIRROR}")"
  echo "  proxy_detected=$(proxy_detected)"
}

main() {
  local command_name="${1:-}"
  [[ -n "${command_name}" ]] || { usage; exit 1; }
  shift || true
  case "${command_name}" in
    detect-env) parse_args "$@"; detect_env ;;
    setup) setup_command "$@" ;;
    dev) dev_command "$@" ;;
    build) build_command "$@" ;;
    doctor) doctor_command "$@" ;;
    --help|-h|help) usage ;;
    *) die "unknown command: ${command_name}" ;;
  esac
}

main "$@"
'''


def render_wrapper(command: str) -> str:
    exec_line = 'exec bash "${' + f'THIS_DIR}}/manage.sh" {command} "$@"'
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "",
            "set -euo pipefail",
            "",
            f"# {GENERATED_MARKER}",
            'THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
            exec_line,
            "",
        ]
    )


def scaffold(
    *,
    root: Path,
    force: bool = False,
    dry_run: bool = False,
    with_wrappers: bool = False,
) -> tuple[Path, ...]:
    root = root.expanduser().resolve()
    profile = discover_profile(root)
    deploy_dir = root / "deploy"
    files: dict[Path, str] = {
        deploy_dir / "manage.sh": render_manage_script(profile),
    }
    if with_wrappers:
        files[deploy_dir / "setup.sh"] = render_wrapper("setup")
        files[deploy_dir / "deploy.sh"] = render_wrapper("build")
        files[deploy_dir / "build.sh"] = render_wrapper("build")

    written: list[Path] = []
    for path, content in files.items():
        if path.exists() and not force and not _is_generated(path):
            raise SystemExit(
                f"refusing to overwrite non-scaffolded file: {path}. "
                "Pass --force after reviewing the existing script."
            )
        if dry_run:
            written.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        _make_executable(path)
        written.append(path)
    return tuple(written)


def _is_generated(path: Path) -> bool:
    try:
        return GENERATED_MARKER in path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False


def _make_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _run_bash_syntax_check(paths: tuple[Path, ...]) -> None:
    shell_paths = [path for path in paths if path.suffix == ".sh"]
    if not shell_paths:
        return
    result = subprocess.run(
        ["bash", "-n", *(str(path) for path in shell_paths)],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise SystemExit((result.stdout + result.stderr).strip())


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Scaffold a project-local deploy/manage.sh from the repository structure."
    )
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="target repository root")
    parser.add_argument("--force", action="store_true", help="overwrite existing scripts")
    parser.add_argument("--dry-run", action="store_true", help="show target paths without writing")
    wrapper_group = parser.add_mutually_exclusive_group()
    wrapper_group.add_argument(
        "--with-wrappers",
        action="store_true",
        help="also write legacy setup/deploy/build wrappers",
    )
    wrapper_group.add_argument(
        "--no-wrappers",
        action="store_true",
        help="deprecated no-op; deploy/manage.sh is the default output",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="run bash -n on generated scripts after writing",
    )
    args = parser.parse_args()

    written = scaffold(
        root=args.root,
        force=args.force,
        dry_run=args.dry_run,
        with_wrappers=args.with_wrappers,
    )
    if args.check and not args.dry_run:
        _run_bash_syntax_check(written)
    for path in written:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
